In [1]:
import pandas as pd

In [2]:
dt = pd.read_csv("vgchartz-2024.csv")

In [ ]:
dt.describe()

,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales
count,6678.000000,18922.000000,12637.000000,6726.000000,12824.000000,15128.000000
mean,7.220440,0.349113,0.264740,0.102281,0.149472,0.043041
std,1.457066,0.807462,0.494787,0.168811,0.392653,0.126643
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.400000,0.030000,0.050000,0.020000,0.010000,0.000000
50%,7.500000,0.120000,0.120000,0.040000,0.040000,0.010000
75%,8.300000,0.340000,0.280000,0.120000,0.140000,0.030000
max,10.000000,20.320000,9.760000,2.130000,9.850000,3.120000

In [ ]:
dt.info()

<class 'pandas.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   img           64016 non-null  str
 1   title         64016 non-null  str
 2   console       64016 non-null  str
 3   genre         64016 non-null  str
 4   publisher     64016 non-null  str
 5   developer     63999 non-null  str
 6   critic_score  6678 non-null   float64
 7   total_sales   18922 non-null  float64
 8   na_sales      12637 non-null  float64
 9   jp_sales      6726 non-null   float64
 10  pal_sales     12824 non-null  float64
 11  other_sales   15128 non-null  float64
 12  release_date  56965 non-null  str
 13  last_update   17879 non-null  str
dtypes: float64(6), str(8)
memory usage: 6.8 MB

In [ ]:
dt.columns

Index(['img', 'title', 'console', 'genre', 'publisher', 'developer',
       'critic_score', 'total_sales', 'na_sales', 'jp_sales', 'pal_sales',
       'other_sales', 'release_date', 'last_update'],
      dtype='str')

In [ ]:
dt.publisher

0              Rockstar Games
1              Rockstar Games
2              Rockstar Games
3              Rockstar Games
4                  Activision
                 ...
64011             Aksys Games
64012    Nippon Ichi Software
64013    Nippon Ichi Software
64014            Idea Factory
64015                 Unknown
Name: publisher, Length: 64016, dtype: str

In [ ]:
dt[['genre', 'publisher', 'developer']]

              genre             publisher             developer
0            Action        Rockstar Games        Rockstar North
1            Action        Rockstar Games        Rockstar North
2            Action        Rockstar Games        Rockstar North
3            Action        Rockstar Games        Rockstar North
4           Shooter            Activision              Treyarch
...             ...                   ...                   ...
64011  Visual Novel           Aksys Games      Arc System Works
64012  Visual Novel  Nippon Ichi Software  Nippon Ichi Software
64013  Visual Novel  Nippon Ichi Software  Nippon Ichi Software
64014  Visual Novel          Idea Factory               Otomate
64015  Visual Novel               Unknown            G.rev Ltd.

[64016 rows x 3 columns]

In [ ]:
dt.iloc[200 : 300 , 6:8 ]

     critic_score  total_sales
200           8.0         3.49
201           8.3         3.48
202           9.0         3.48
203           7.6         3.47
204           7.1         3.46
..            ...          ...
295           NaN         2.79
296           8.0         2.79
297           NaN         2.79
298           NaN         2.79
299           NaN         2.79

[100 rows x 2 columns]

In [ ]:
dt.loc[200:300 ,['genre', 'developer']]

        genre                  developer
200    Sports                  EA Canada
201   Shooter           Gearbox Software
202   Shooter    EA Digital Illusions CE
203    Sports                       Sega
204      Misc          Vicarious Visions
..        ...                        ...
296    Action               Toys for Bob
297  Fighting                     Yuke's
298  Fighting         Avalanche Software
299    Sports  Camelot Software Planning
300  Platform          Traveller's Tales

[101 rows x 2 columns]

In [ ]:
dt[dt["developer"].str.contains("rockstar", case=False)]

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
7,/games/boxart/full_4653215AmericaFrontccc.jpg,Red Dead Redemption 2,PS4,Action-Adventure,Rockstar Games,Rockstar Games,9.8,13.94,5.26,0.21,6.21,2.26,2018-10-26,2018-11-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46916,/games/boxart/8738169ccc.jpg,Smuggler's Run 2: Hostile Territory,PS2,Racing,Rockstar Games,Rockstar San Diego,NaN,NaN,NaN,NaN,NaN,NaN,2001-10-30,NaN
52024,/games/boxart/full_6787331AmericaFrontccc.jpg,Max Payne 3,All,Shooter,Rockstar Games,Rockstar Studios,NaN,NaN,NaN,NaN,NaN,NaN,2012-05-15,2020-11-06
52094,/games/boxart/full_9900194AmericaFrontccc.jpg,Max Payne 3,PC,Shooter,Rockstar Games,Rockstar Vancouver,9.0,NaN,NaN,NaN,NaN,NaN,2012-05-29,NaN
52406,/games/boxart/default.jpg,Agent,PS3,Shooter,Rockstar Games,Rockstar North,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-31,NaN
59819,/games/boxart/full_rockstar-games-presents-tab...,Rockstar Games presents Table Tennis,XBL,Sports,Rockstar Games,Rockstar San Diego,NaN,NaN,NaN,NaN,NaN,NaN,2009-08-11,NaN

In [ ]:
dt[(dt["developer"].str.contains("rockstar", case=False , na=False)) & (dt["genre"].str.contains("shooter", case=False , na=False))]

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
587,/games/boxart/full_4250605AmericaFrontccc.jpg,Max Payne 3,PS3,Shooter,Rockstar Games,Rockstar Vancouver,NaN,1.86,0.59,0.06,0.93,0.27,2012-05-15,NaN
723,/games/boxart/full_6497876AmericaFrontccc.jpg,Max Payne 3,X360,Shooter,Rockstar Games,Rockstar Vancouver,NaN,1.63,0.86,0.01,0.62,0.13,2012-05-15,2018-02-08
867,/games/boxart/7620922ccc.jpg,Red Dead Revolver,PS2,Shooter,Rockstar Games,Rockstar San Diego,NaN,1.45,0.71,NaN,0.55,0.19,2004-05-03,NaN
3045,/games/boxart/2928172ccc.jpg,Red Dead Revolver,XB,Shooter,Rockstar Games,Rockstar San Diego,NaN,0.55,0.40,NaN,0.12,0.02,2004-05-03,NaN
52024,/games/boxart/full_6787331AmericaFrontccc.jpg,Max Payne 3,All,Shooter,Rockstar Games,Rockstar Studios,NaN,NaN,NaN,NaN,NaN,NaN,2012-05-15,2020-11-06
52094,/games/boxart/full_9900194AmericaFrontccc.jpg,Max Payne 3,PC,Shooter,Rockstar Games,Rockstar Vancouver,9.0,NaN,NaN,NaN,NaN,NaN,2012-05-29,NaN
52406,/games/boxart/default.jpg,Agent,PS3,Shooter,Rockstar Games,Rockstar North,NaN,NaN,NaN,NaN,NaN,NaN,2020-12-31,NaN

In [ ]:
dt[dt["genre"].str.contains("Action", case=False , na=False)]

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
7,/games/boxart/full_4653215AmericaFrontccc.jpg,Red Dead Redemption 2,PS4,Action-Adventure,Rockstar Games,Rockstar Games,9.8,13.94,5.26,0.21,6.21,2.26,2018-10-26,2018-11-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30615,/games/boxart/full_4257832AmericaFrontccc.jpg,Yakuza: Like A Dragon,XS,Action-Adventure,Sega,Sega,NaN,NaN,NaN,NaN,NaN,NaN,2020-11-10,2020-05-07
30616,/games/boxart/full_965332AmericaFrontccc.jpg,Yomawari: Lost in the Dark,All,Action-Adventure,Unknown,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-31
30617,/games/boxart/full_6073579AmericaFrontccc.jpg,Yomawari: Lost in the Dark,NS,Action-Adventure,Unknown,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-31
30618,/games/boxart/full_6684830AmericaFrontccc.jpg,Yomawari: Lost in the Dark,PS4,Action-Adventure,Unknown,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-05-31
30619,/games/boxart/full_4254556AmericaFrontccc.jpg,Zelda's Adventure,CDi,Action-Adventure,Philips Interactive Media,Viridis Corporation,NaN,NaN,NaN,NaN,NaN,NaN,1994-06-05,2018-04-17

In [ ]:
dt["developer"].unique()

<StringArray>
[          'Rockstar North',                 'Treyarch',
            'Infinity Ward',           'Rockstar Games',
       'Sledgehammer Games',               'DMA Design',
             'EA Vancouver',                'EA Canada',
                   'Bungie',           '343 Industries',
 ...
                  'PALETTE',         'bch waves studio',
        'Black Tabby Games', 'Future Tech Lab Co.,Ltd.',
                 'Radi Art',               'Tales Shop',
               'Novectacle',          'Different Tales',
            '4D Door Games',              'InvertMouse']
Length: 8863, dtype: str

In [ ]:
dt.developer.unique()

<StringArray>
[          'Rockstar North',                 'Treyarch',
            'Infinity Ward',           'Rockstar Games',
       'Sledgehammer Games',               'DMA Design',
             'EA Vancouver',                'EA Canada',
                   'Bungie',           '343 Industries',
 ...
                  'PALETTE',         'bch waves studio',
        'Black Tabby Games', 'Future Tech Lab Co.,Ltd.',
                 'Radi Art',               'Tales Shop',
               'Novectacle',          'Different Tales',
            '4D Door Games',              'InvertMouse']
Length: 8863, dtype: str

In [ ]:
# Genre ke hisaab se group karke count nikaalna
dt.groupby("genre")["title"].count()

genre
Action              8557
Action-Adventure    1877
Adventure           6260
Board Game            33
Education             35
Fighting            2367
MMO                  115
Misc                9304
Music                297
Party                151
Platform            4001
Puzzle              3521
Racing              3425
Role-Playing        5721
Sandbox               20
Shooter             5410
Simulation          3158
Sports              5586
Strategy            3685
Visual Novel         493
Name: title, dtype: int64

In [ ]:
dt.groupby("title").count()

,img,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
title,,,,,,,,,,,,,
"""Nuke It""",1,1,1,1,1,0,0,0,0,0,0,1,1
#DRIVE Rally,6,6,6,6,6,0,0,0,0,0,0,0,6
#IDARB,1,1,1,1,1,0,0,0,0,0,0,1,0
#killallzombies,1,1,1,1,1,0,0,0,0,0,0,1,1
'70s Robot Anime: Geppy-X,1,1,1,1,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
yOm,1,1,1,1,1,0,0,0,0,0,0,1,0
yOm_fury,1,1,1,1,1,0,0,0,0,0,0,1,0
¡Shin Chan Flipa en colores!,1,1,1,1,1,0,1,0,1,0,0,1,0
じんるいのみなさまへ,1,1,1,1,1,0,0,0,0,0,0,0,1
レミロア~少女と異世界と魔導書,1,1,1,1,1,0,0,0,0,0,0,0,1

In [ ]:
dt.title

0                      Grand Theft Auto V
1                      Grand Theft Auto V
2             Grand Theft Auto: Vice City
3                      Grand Theft Auto V
4               Call of Duty: Black Ops 3
                       ...
64011               XBlaze Lost: Memories
64012                        Yoru, Tomosu
64013                        Yoru, Tomosu
64014     Yunohana SpRING! ~Mellow Times~
64015    Yurukill: The Calumniation Games
Name: title, Length: 64016, dtype: str

In [ ]:
dt.groupby("developer")["title"].count().sort_values(ascending= False)

developer
Unknown        4435
Konami          976
Sega            915
Capcom          870
Namco           489
               ...
toddm             1
tricktale         1
tritoneTech       1
trufun101         1
unilever          1
Name: title, Length: 8862, dtype: int64

In [ ]:
dt.groupby("developer")["total_sales"].sum()

developer
.theprodukkt              0.00
07th Expansion            0.20
0verflow                  0.02
100 Stones Interactive    0.00
1047 Games                0.00
                          ...
yuwaka                    0.00
yyr                       0.00
zSlide                    0.03
zerozerozero              0.00
zio3                      0.00
Name: total_sales, Length: 8862, dtype: float64

In [ ]:
dt.columns

Index(['img', 'title', 'console', 'genre', 'publisher', 'developer',
       'critic_score', 'total_sales', 'na_sales', 'jp_sales', 'pal_sales',
       'other_sales', 'release_date', 'last_update'],
      dtype='str')

In [ ]:
dt.groupby("developer").agg({
        "title": "count",
        "publisher" : "nunique" ,
        "release_date" : "count"
    }).reset_index()

                   developer  title  publisher  release_date
0               .theprodukkt      1          1             1
1             07th Expansion      9          4             9
2                   0verflow      2          2             2
3     100 Stones Interactive      2          1             0
4                 1047 Games      1          1             0
...                      ...    ...        ...           ...
8857                  yuwaka      2          2             1
8858                     yyr      3          1             3
8859                  zSlide      1          1             1
8860            zerozerozero      1          1             1
8861                    zio3      1          1             1

[8862 rows x 4 columns]

In [ ]:
dt["developer"].shape

(64016,)

In [ ]:
dt.groupby("developer")["title"].count().reset_index().sort_values(by = "title" , ascending=False )

        developer  title
8014      Unknown   4435
4155       Konami    976
6631         Sega    915
1340       Capcom    870
5107        Namco    489
...           ...    ...
8839        toddm      1
8842    tricktale      1
8843  tritoneTech      1
8844    trufun101      1
8845     unilever      1

[8862 rows x 2 columns]

In [ ]:
dt.groupby("publisher").agg(
    {
        "img" : "count",
        "title" : "count",
        "total_sales" : "sum"

    }
).reset_index().sort_values(by= "title" , ascending= False)

            publisher   img  title  total_sales
3062          Unknown  8842   8842        15.92
2540             Sega  2207   2207       206.38
3043          Ubisoft  1663   1663       462.57
852   Electronic Arts  1619   1619       644.13
101        Activision  1582   1582       722.77
...               ...   ...    ...          ...
3331        gamesbymo     1      1         0.00
1112        GamesCafe     1      1         0.00
1113  GamesCafe, Inc.     1      1         0.00
3355         lbxgames     1      1         0.00
3357     like Charlie     1      1         0.00

[3383 rows x 4 columns]

In [ ]:
daata = {






"name" :[	"Aarav" 	, "Rohan" , "Neha"	, "Priya"	 , "Karan" , "Ankit" ],		

 	
"Sales" :[  30000 , 40000 , 25000 , 35000 , 30000 , 50000] ,


"sector" :[ "IT" , "sales" , "HR" , "IT" , "sales" , "IT" ]			
	

}
result = pd.DataFrame(daata)
result

    name  Sales sector
0  Aarav  30000     IT
1  Rohan  40000  sales
2   Neha  25000     HR
3  Priya  35000     IT
4  Karan  30000  sales
5  Ankit  50000     IT

In [ ]:
df=pd.DataFrame(daata)

In [ ]:
result.groupby("sector")

In [ ]:
result.groupby("sector")["Sales"].mean()

sector
HR       25000.000000
IT       38333.333333
sales    35000.000000
Name: Sales, dtype: float64

In [ ]:
result.groupby("sector")["Sales"].sum()

sector
HR        25000
IT       115000
sales     70000
Name: Sales, dtype: int64

In [ ]:
result.groupby("sector")["Sales"].count()

sector
HR       1
IT       3
sales    2
Name: Sales, dtype: int64

In [ ]:
result.groupby("sector")["Sales"].min()

sector
HR       25000
IT       30000
sales    30000
Name: Sales, dtype: int64

In [ ]:
result.groupby("sector")["Sales"].agg (
    total_sales = "sum" ,
    average_sales = ("mean") ).reset_index()

  sector  total_sales  average_sales
0     HR        25000   25000.000000
1     IT       115000   38333.333333
2  sales        70000   35000.000000

In [ ]:
result.groupby(["sector" , "name"])["Sales"] .agg(
    total_sales = "sum" ,
    average_sales = "mean"

).reset_index()

  sector   name  total_sales  average_sales
0     HR   Neha        25000        25000.0
1     IT  Aarav        30000        30000.0
2     IT  Ankit        50000        50000.0
3     IT  Priya        35000        35000.0
4  sales  Karan        30000        30000.0
5  sales  Rohan        40000        40000.0

In [ ]:
result.groupby("sector")["Sales"].agg(

    Total_Sales = "sum",
    Average_Sales = "mean",
    Maximum_Sales = "max",
    Minimum_Sales = "min"
).reset_index()

  sector  Total_Sales  Average_Sales  Maximum_Sales  Minimum_Sales
0     HR        25000   25000.000000          25000          25000
1     IT       115000   38333.333333          50000          30000
2  sales        70000   35000.000000          40000          30000

In [ ]:
result.groupby("sector")["Sales"].agg(

    Total_Sales = "sum",
    Average_Sales = "mean",
    number_of_sales = "count"
).reset_index()

  sector  Total_Sales  Average_Sales  number_of_sales
0     HR        25000   25000.000000                1
1     IT       115000   38333.333333                3
2  sales        70000   35000.000000                2

In [ ]:
result.groupby("sector")["Sales"].agg(
    Maximum_Sales = "max",

    Minimum_Sales = "min",

    Total_Sales = "sum"
).reset_index().sort_values (by= "sector" ,ascending= True)

  sector  Maximum_Sales  Minimum_Sales  Total_Sales
0     HR          25000          25000        25000
1     IT          50000          30000       115000
2  sales          40000          30000        70000

In [ ]:
result.groupby(["sector" , "name"])["Sales"].agg(
    Maximum_Sales = "max",
    Total_Sales = "sum"
).reset_index().sort_values (by= "Total_Sales" , ascending= True)

  sector   name  Maximum_Sales  Total_Sales
0     HR   Neha          25000        25000
1     IT  Aarav          30000        30000
4  sales  Karan          30000        30000
3     IT  Priya          35000        35000
5  sales  Rohan          40000        40000
2     IT  Ankit          50000        50000

In [3]:

dt.isnull().sum()

img                 0
title               0
console             0
genre               0
publisher           0
developer          17
critic_score    57338
total_sales     45094
na_sales        51379
jp_sales        57290
pal_sales       51192
other_sales     48888
release_date     7051
last_update     46137
dtype: int64

In [ ]:
dt["developer"] = dt["developer"].fillna("umair")

In [7]:
dt.developer.str.contains("umair" , case= False )

0        False
1        False
2        False
3        False
4        False
         ...
64011    False
64012    False
64013    False
64014    False
64015    False
Name: developer, Length: 64016, dtype: bool

In [9]:
dt['developer'].isnull().sum

<bound method Series.sum of 0        False
1        False
2        False
3        False
4        False
         ...
64011    False
64012    False
64013    False
64014    False
64015    False
Name: developer, Length: 64016, dtype: bool>

In [10]:
dt[dt["developer"] == "umair"]

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
8486,/games/boxart/21030ccc.jpg,Gourmet Chef: Cook Your Way to Fame,DS,Misc,Ubisoft,umair,NaN,0.14,0.13,NaN,NaN,0.01,2008-06-24,NaN
10832,/games/boxart/2426879ccc.jpg,Wordmaster,DS,Strategy,"Destination Software, Inc",umair,NaN,0.09,0.09,NaN,0.0,0.01,2008-08-12,NaN
18185,/games/boxart/8436780ccc.jpg,SAS: Secure Tomorrow,PC,Shooter,City Interactive,umair,NaN,0.00,NaN,NaN,0.0,0.00,2008-10-16,NaN
18455,/games/boxart/default.jpg,My Baby and Me,Wii,Misc,Unknown,umair,NaN,0.00,NaN,NaN,0.0,NaN,NaN,NaN
19925,/games/boxart/default.jpg,Bounty Hunter,PC,Action,Unknown,umair,NaN,NaN,NaN,NaN,NaN,NaN,1999-11-30,NaN
25045,/games/boxart/default.jpg,Abandoner,PC,Adventure,Unknown,umair,NaN,NaN,NaN,NaN,NaN,NaN,2004-09-17,NaN
27407,/games/boxart/full_7747476AmericaFrontccc.jpg,The Enchanted Unicorn,PC,Adventure,Take-Two Interactive,umair,NaN,NaN,NaN,NaN,NaN,NaN,2008-09-16,NaN
31230,/games/boxart/full_8222233PALFrontccc.png,istanbul Beyleri,PC,Fighting,Unknown,umair,NaN,NaN,NaN,NaN,NaN,NaN,2006-12-17,NaN
37057,/games/boxart/1105699ccc.jpg,Purrfect Pet Shop,PC,Misc,eGames,umair,NaN,NaN,NaN,NaN,NaN,NaN,2008-06-13,NaN
40753,/games/boxart/default.jpg,Duludubi Star,PC,Platform,Unknown,umair,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43679,/games/boxart/default.jpg,Finkles Adventure,Wii,Puzzle,Unknown,umair,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43831,/games/boxart/full_6465496AmericaFrontccc.jpg,Hidden Mysteries: Buckingham Palace,PC,Puzzle,Unknown,umair,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50450,/games/boxart/101505ccc.jpg,The Orb & the Oracle,PC,Role-Playing,Unknown,umair,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50592,/games/boxart/default.jpg,VIVA Fighter,PC,Role-Playing,Unknown,umair,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55431,/games/boxart/full_6511154AmericaFrontccc.png,My Friend Pedro,NS,Shooter,Devolver Digital,umair,NaN,NaN,NaN,NaN,NaN,NaN,2019-06-20,2019-06-10
55432,/games/boxart/full_6946845AmericaFrontccc.jpg,My Friend Pedro,PC,Shooter,Devolver Digital,umair,NaN,NaN,NaN,NaN,NaN,NaN,2019-06-20,2019-06-10
62494,/games/boxart/default.jpg,Panzer Elite General,PC,Strategy,JoWood Productions,umair,NaN,NaN,NaN,NaN,NaN,NaN,2001-12-07,NaN