In [ ]:
import pandas as pd

In [6]:
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\asus\appdata\roaming\python\python314\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\users\asus\appdata\roaming\python\python314\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\asus\appdata\roaming\python\python314\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in c:\users\asus\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
import pandas as pd

a = [1,2,3,4,5,6]
b = pd.Series(a , index = ["q" , "q" , '4' , 'q' , 'y' , 'u'])
print(b)

q    1
q    2
4    3
q    4
y    5
u    6
dtype: int64

In [8]:
info ={ 
    "name" : "umair",
    "age" : 45,
    "class" : "pandas"
}

result =pd.Series(info)
result

name      umair
age          45
class    pandas
dtype: object

In [9]:
data = { 
    "name" : ["Mukesh" , "ramesh" , "suresh" ],
    "age" : [23 , 44 , 56] ,
    "cast" : ["mochi" , "teli" , "gurjer"]
}
result = pd.DataFrame(data)
result

     name  age    cast
0  Mukesh   23   mochi
1  ramesh   44    teli
2  suresh   56  gurjer

In [10]:
data = [
       ["Mukesh" , 30, "mochi" ],
       ["mramesh" , 44 , "teli"] ,
       ["suresh" , 34 , "gurjer"]
]

info = pd.DataFrame(data , columns = ["name" , "age" , "cast"])
info

      name  age    cast
0   Mukesh   30   mochi
1  mramesh   44    teli
2   suresh   34  gurjer

In [11]:
data = pd.read_csv("vgchartz-2024.csv")
data

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64011,/games/boxart/full_2779838AmericaFrontccc.jpg,XBlaze Lost: Memories,PC,Visual Novel,Aksys Games,Arc System Works,NaN,NaN,NaN,NaN,NaN,NaN,2016-08-11,2019-01-28
64012,/games/boxart/full_8031506AmericaFrontccc.jpg,"Yoru, Tomosu",PS4,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30,2020-05-09
64013,/games/boxart/full_6553045AmericaFrontccc.jpg,"Yoru, Tomosu",NS,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30,2020-05-09
64014,/games/boxart/full_6012940JapanFrontccc.png,Yunohana SpRING! ~Mellow Times~,NS,Visual Novel,Idea Factory,Otomate,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-28,2019-02-24
64015,/games/boxart/default.jpg,Yurukill: The Calumniation Games,PS4,Visual Novel,Unknown,G.rev Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-29

In [12]:
df = pd.DataFrame(data)

In [13]:
data.columns
data

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64011,/games/boxart/full_2779838AmericaFrontccc.jpg,XBlaze Lost: Memories,PC,Visual Novel,Aksys Games,Arc System Works,NaN,NaN,NaN,NaN,NaN,NaN,2016-08-11,2019-01-28
64012,/games/boxart/full_8031506AmericaFrontccc.jpg,"Yoru, Tomosu",PS4,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30,2020-05-09
64013,/games/boxart/full_6553045AmericaFrontccc.jpg,"Yoru, Tomosu",NS,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,NaN,NaN,NaN,NaN,NaN,NaN,2020-07-30,2020-05-09
64014,/games/boxart/full_6012940JapanFrontccc.png,Yunohana SpRING! ~Mellow Times~,NS,Visual Novel,Idea Factory,Otomate,NaN,NaN,NaN,NaN,NaN,NaN,2019-02-28,2019-02-24
64015,/games/boxart/default.jpg,Yurukill: The Calumniation Games,PS4,Visual Novel,Unknown,G.rev Ltd.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-09-29

In [14]:
data.developer

0              Rockstar North
1              Rockstar North
2              Rockstar North
3              Rockstar North
4                    Treyarch
                 ...
64011        Arc System Works
64012    Nippon Ichi Software
64013    Nippon Ichi Software
64014                 Otomate
64015              G.rev Ltd.
Name: developer, Length: 64016, dtype: str

In [15]:

data = {
    "name" : ["umair" , "siddiqui" , "ahmed"],
    "age"  :  [24, 34 , 45 ] ,
    "colony" : ["ramkalliyan" , "ram viahr " , "kelash pervat "]
}

a = pd.DataFrame(data)
a

       name  age          colony
0     umair   24     ramkalliyan
1  siddiqui   34      ram viahr
2     ahmed   45  kelash pervat

In [18]:
data.columns
data

AttributeError: 'dict' object has no attribute 'columns'

In [ ]:
data[["console" , "genre" , "publisher"]]

      console         genre             publisher
0         PS3        Action        Rockstar Games
1         PS4        Action        Rockstar Games
2         PS2        Action        Rockstar Games
3        X360        Action        Rockstar Games
4         PS4       Shooter            Activision
...       ...           ...                   ...
64011      PC  Visual Novel           Aksys Games
64012     PS4  Visual Novel  Nippon Ichi Software
64013      NS  Visual Novel  Nippon Ichi Software
64014      NS  Visual Novel          Idea Factory
64015     PS4  Visual Novel               Unknown

[64016 rows x 3 columns]

In [ ]:
data.describe()

,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales
count,6678.000000,18922.000000,12637.000000,6726.000000,12824.000000,15128.000000
mean,7.220440,0.349113,0.264740,0.102281,0.149472,0.043041
std,1.457066,0.807462,0.494787,0.168811,0.392653,0.126643
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.400000,0.030000,0.050000,0.020000,0.010000,0.000000
50%,7.500000,0.120000,0.120000,0.040000,0.040000,0.010000
75%,8.300000,0.340000,0.280000,0.120000,0.140000,0.030000
max,10.000000,20.320000,9.760000,2.130000,9.850000,3.120000

In [ ]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   img           64016 non-null  str
 1   title         64016 non-null  str
 2   console       64016 non-null  str
 3   genre         64016 non-null  str
 4   publisher     64016 non-null  str
 5   developer     63999 non-null  str
 6   critic_score  6678 non-null   float64
 7   total_sales   18922 non-null  float64
 8   na_sales      12637 non-null  float64
 9   jp_sales      6726 non-null   float64
 10  pal_sales     12824 non-null  float64
 11  other_sales   15128 non-null  float64
 12  release_date  56965 non-null  str
 13  last_update   17879 non-null  str
dtypes: float64(6), str(8)
memory usage: 6.8 MB

In [ ]:
data.columns
data

AttributeError: 'dict' object has no attribute 'columns'

In [ ]:
ass = data.loc[300 : 500 ,["console" , "genre" , "publisher"]]
a

AttributeError: 'dict' object has no attribute 'loc'

In [ ]:
acc = data.iloc[1000 : 2000 , 6 : 9]

acc

AttributeError: 'dict' object has no attribute 'iloc'